---
title: "Case Study"
output: github_document
---

Today we're studying a case.

```{r, include = FALSE,message=FALSE,warning=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Get Data

```{r}
library(p8105.datasets)

data(nyc_airbnb)

nyc_airbnb= 
  nyc_airbnb %>% 
  rename(borough=neighbourhood_group) %>% 
  mutate(stars=review_scores_location/2)
```

## Brainstorm questions
* what variables are relevant to higher review/ scores?
```{r q1}

```

* what are the popular places to rent an airbnb?
```{r q2}
q2 = nyc_airbnb %>%
  group_by(neighbourhood, neighbourhood_group) %>%
  distinct () %>%
  summarize(n_obs = n()) %>% 
  ungroup() %>% 
  group_by(neighbourhood_group) %>% 
  mutate(rank=min_rank(desc(n_obs))) %>% 
  filter (rank > 5) %>% 
  arrange(neighbourhood_group,n_obs)

q2
```

* what makes an airbnb more expensive?
```{r q3}
nyc_airbnb %>% 
  group_by(borough, room_type) %>% 
  summarize (
    mean_price= mean(price, na.rm= TRUE)
  ) %>% 
  pivot_wider (
    names_from = room_type, 
    values_from = mean_price, 
  )
```

look at price distribution!

```{r plots}
nyc_airbnb %>% 
  filter(borough== "Manhattan", 
         price< 1000) %>% 
  ggplot(aes(x=price))+
  geom_histogram() +
  facet_grid (. ~ room_type)
```

* what portion of hosts/ locations are private rooms vs entire apartment?
```{r q4}
nyc_q4 <- nyc_airbnb %>% 
  drop_na() %>% 
  janitor::clean_names() %>% 
  group_by(room_type) %>% 
  summarize(n_obs = n())
```

price vs ranking?

```{r}
nyc_airbnb %>% 
  filter(borough== "Manhattan") %>% 
  ggplot(aes(x=stars,y =price))+
  geom_point() +
  facet_grid (. ~ room_type)
```

somewhat fancier box plot...

```{r}
nyc_airbnb %>% 
  filter(borough== "Manhattan") %>% 
  group_by(neighbourhood) %>% 
  summarize(mean_price=mean(price, na.rm=TRUE)) %>% 
  arrange(desc(mean_price))
```

```{r}
nyc_airbnb %>% 
  filter(borough== "Manhattan",
         room_type=="Entire home/apt") %>% 
  filter(price <=1000) %>% 
  mutate(neighbourhood=fct_reorder(neighbourhood, price)) %>% 
  ggplot(aes(x=neighbourhood, y=price))+
  geom_boxplot() +
  coord_flip()
```

Price vs location

```{r}
nyc_airbnb %>% 
  filter(borough== "Manhattan",
         room_type=="Entire home/apt") %>% 
  filter(price <=1000) %>% 
  sample_n(2000) %>% 
  ggplot(aes(x=lat, y=long, color=price))+
  geom_point(alpha=0.5)
```

